name: Build and Publish to GHCR

on:
  push:
    branches:
      - main  # Runs on push to main branch
  pull_request:
    branches:
      - main  # Runs on PR to main branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write  # Needed to push to GHCR

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | podman login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build the container image
        run: |
          IMAGE_NAME=ghcr.io/harish2704/apache-php8-systemd-container
          podman build -t $IMAGE_NAME:latest .

      - name: Push the image to GitHub Container Registry
        run: |
          IMAGE_NAME=ghcr.io/harish2704/apache-php8-systemd-container
          podman push $IMAGE_NAME:latest
